apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
spec:
  selector:
    app: {{ .Release.Name }}-db
  ports:
    - protocol: TCP
      port: {{ .Values.db.ports.hostPort }}
      targetPort: {{ .Values.db.ports.containerPort }}