apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-webserver
spec:
  selector:
    app: {{ .Release.Name }}-webserver
  ports:
    - protocol: TCP
      port: {{ .Values.webserver.ports[0].hostPort }}
      targetPort: {{ .Values.webserver.ports[0].containerPort }}
  